"""add_tag

Revision ID: 3b89d8314b1d
Revises: 5fe8ff44267e
Create Date: 2025-04-13 20:12:34.022435

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3b89d8314b1d'
down_revision = '5fe8ff44267e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 