"""add_slug

Revision ID: 5fe8ff44267e
Revises: 01
Create Date: 2025-04-13 20:06:37.724373

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '5fe8ff44267e'
down_revision = '01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.create_index(op.f('ix_article_slug'), 'article', ['slug'], unique=True)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_article_slug'), table_name='article')
    op.drop_column('article', 'slug')
    # ### end Alembic commands ### 