"""update article

Revision ID: c6e96e88e4b8
Revises: 
Create Date: 2025-04-14 04:30:57.130849

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c6e96e88e4b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('article', sa.Column('footer_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'footer_content')
    op.drop_column('article', 'excerpt')
    # ### end Alembic commands ### 